### ISSUE TITLE
NC-SA-2019-004 has content of NC-SA-2020-004

### ISSUE THREAD

**Issue by cfi-gb** [nextcloud/security-advisories#19]
I would like to point out that the following advisory:

https://nextcloud.com/security/advisory/?id=NC-SA-2019-004 (Reflected XSS in svg logo generation (NC-SA-2019-004))

has currently the following text:

Bypass lock protection in Android app (NC-SA-2019-004)

and the content of:

https://nextcloud.com/security/advisory/?id=NC-SA-2020-004 (Bypass lock protection in Android app (NC-SA-2020-004))

**Comment by cfi-gb** [comment]
It seems https://github.com/nextcloud/security-advisories/blob/master/server/nc-sa-2019-004.json has the correct content so this could be just a deployment / web page problem.

**Comment by nickvergessen** [comment]
Actually the mistake is that the ID `nc-sa-2019-004` is used twice:
* Android: https://github.com/nextcloud/security-advisories/blob/904d781120f40fa40756e7909b7d590d6251a88d/android/nc-sa-2019-004.json
* Server: https://github.com/nextcloud/security-advisories/blob/904d781120f40fa40756e7909b7d590d6251a88d/server/nc-sa-2019-004.json

Sorry about the trouble. I renamed the server one (because it has the later timestamp) to 2019-018 I will see if it is possible to update the link on the CVE
